################################################################################
# Triggered for deployment status changes
# https://vercel.com/support/articles/how-do-i-get-notified-when-my-vercel-deployment-fails
################################################################################

name: Deployment change notification
on: [deployment_status]

jobs:
  add-failure-comment:
    name: Add a comment to the commit that caused the failure
    if: github.event.deployment_status.state == 'failure'
    runs-on: ubuntu-latest

    steps:
      - name: Add commit comment - failure
        run: |
          curl -L -X POST \
          --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "body": "Deployment has failed."
            }'

  slack-notification:
    name: Send a Slack Webhook when deployment status changes
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification - success
        run: |
          curl -X POST \
          --data-urlencode "payload={\"channel\": \"#notifications\", \"username\": \"webhookbot\", \"text\": \"This is posted to #notifications and comes from a bot named webhookbot.\", \"icon_emoji\": \":robot_face:\"}" \
          https://hooks.slack.com/services/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
